// TEXT WIDGETS
export const WIDGET_TITLE = 'WIDGET_TITLE';
export const WIDGET_LABEL = 'WIDGET_LABEL';

// FORM CONTROL WIDGETS
export const WIDGET_INPUT_TEXT = 'WIDGET_INPUT_TEXT';
export const WIDGET_INPUT_RADIO = 'WIDGET_INPUT_RADIO';
export const WIDGET_INPUT_CHECKBOX = 'WIDGET_INPUT_CHECKBOX';
export const WIDGET_INPUT_TEXTAREA = 'WIDGET_INPUT_TEXTAREA';
export const WIDGET_INPUT_DROPDOWN = 'WIDGET_INPUT_DROPDOWN';

// Container
export const WIDGET_PANEL = 'WIDGET_PANEL';
