export const INIT_APP = 'INIT_APP';

export const NEW_TITLE = 'NEW_TITLE';
export const NEW_LABEL = 'NEW_LABEL';
export const NEW_TEXT_INPUT = 'NEW_TEXT_INPUT';
export const NEW_PANEL= 'NEW_PANEL';
export const NEW_CHECKBOX = 'NEW_CHECKBOX';
export const NEW_RADIO = 'NEW_RADIO';
export const NEW_TEXTAREA = 'NEW_TEXTAREA';
export const NEW_DROPDOWN = 'NEW_DROPDOWN';

export const UPDATE_LAYOUT = 'UPDATE_LAYOUT';

export const MULTI_SELECT_WIDGET = 'MULTI_SELECT_WIDGET';
export const SELECT_WIDGET = 'SELECT_WIDGET';
export const UNSELECT_ALL = 'UNSELECT_ALL';
export const DRAG_SELECT = 'DRAG_SELECT';
export const MOVE_WIDGET = 'MOVE_WIDGET';
export const DRAG_WIDGET = 'DRAG_WIDGET';
export const DRAG_WIDGETS = 'DRAG_WIDGETS';
export const UPDATE_WIDGET = 'UPDATE_WIDGET';
export const ALIGN_WIDGETS = 'ALIGN_WIDGETS';
export const DELETE_WIDGETS = 'DELETE_WIDGETS';
export const RESIZE_WIDGET = 'RESIZE_WIDGET';
export const UPDATE_DROPDOWN_OPTION = 'UPDATE_DROPDOWN_OPTION';
export const DELETE_DROPDOWN_OPTION = 'DELETE_DROPDOWN_OPTION';
export const ADD_DROPDOWN_OPTION = 'ADD_DROPDOWN_OPTION';

export const ALIGN_DIR_TOP='ALIGN_DIR_TOP';
export const ALIGN_DIR_BOTTOM='ALIGN_DIR_BOTTOM';
export const ALIGN_DIR_LEFT='ALIGN_DIR_LEFT';
export const ALIGN_DIR_RIGHT='ALIGN_DIR_RIGHT';

export const SYSTEM_TOGGLE_GRID = 'SYSTEM_TOGGLE_GRID';
