// TEXT WIDGETS
export const WIDGET_TITLE = 'WIDGET_TITLE';
export const WIDGET_LABEL = 'WIDGET_LABEL';

// FORM CONTROL WIDGETS
export const WIDGET_INPUT_TEXT = 'WIDGET_INPUT_TEXT';
export const WIDGET_INPUT_RADIO = 'WIDGET_INPUT_RADIO';
export const WIDGET_INPUT_CHECKBOX = 'WIDGET_INPUT_CHECKBOX';
export const WIDGET_INPUT_PASSWORD = 'WIDGET_INPUT_PASSWORD';
export const WIDGET_INPUT_TEXTAREA = 'WIDGET_INPUT_TEXTAREA';
export const WIDGET_INPUT_DROPDOWN = 'WIDGET_INPUT_DROPDOWN';

// Container
export const WIDGET_PANEL = 'WIDGET_PANEL';

// DND
export const WIDGET_DRAGGABLE = 'WIDGET_DRAGGABLE';
export const CANVAS_DRAGGABLE = 'CANVAS_DRAGGABLE';
export const SELECT_INDICATOR = 'SELECT_INDICATOR';
export const DRAG_SELECT_RECT = 'DRAG_SELECT_RECT';
